# Site settings
title: code 4 swift
email: cyin15288@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  swift is bester!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jydemo.github.io" # the base hostname & protocol for your site
twitter_username: cyin15288
github_username:  jydemo

# Build settings
markdown: kramdown

paginate: 4

author: yin

gems: [jekyll-paginate]
